/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myapp2;

public class App {

    public String getGreeting() {
        return "Hello progzwei!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
